# Copyright (c) 2022 AVI-SPL Inc.
# All Rights Reserved.
#
# Prerequisites:
# - Security : tag(s) name(s) must have been verified beforehand, this action does not do any validity check
# - Linux docker (cli) command must be available on current runner
# - All files required for building the image must be present on the disk at expected location
# - TODO non self-hosted runner - document prerequisites : credentials for accessing to Docker registry
name: 'Docker build (tag push)'
description: 'Docker build, optionally tag and push to Docker registry'
inputs:
  docker-file:
    description: 'The path of the Dockerfile to be built'
    required: true
  docker-build-other-options:
    description: |
      Additional arguments to the docker build command, added as is at the end of command
      before the path to build directory
    required: false
    type: string
    default: ''
  docker-tag-push:
    description: 'Whether to tag and push docker image'
    required: true
  docker-tags:
    description: >
      Coma separated list of tags to set on built docker image, e.g. "1.1.0.202204051407", "qa".
      Mandatory when docker-file is "docker-tag-push" is "true"
    required: true
  docker-image-prefix:
    description: >
      The prefix to image name used for tagging built docker image,
      e.g. "https://registry.vnocsymphony.com/harbor/projects/74/repositories/symphony-notifications-email"
      Mandatory when "docker-tag-push" is "true"
    required: true
outputs:
  docker-pushed:
    description: "(boolean) Indicates whether or not docker image has been pushed to the registry"
    value: ${{ steps.docker_build_tag_push.outputs.DOCKER_PUSHED }}
runs:
  using: 'composite'
  steps:
    - name: Docker build tag push
      id: docker_build_tag_push
      run: |
        echo "Docker build tag push"
        # WARNING need to use sudo to run docker commands

        # Ensure docker-file has been specified
        if [[ -z "${{ inputs.docker-file }}" ]]; then
          echo "[ERROR] Dockerfile must be specified"
          exit 1
        fi

        # TODO non self-hosted runner - handle credentials to private docker registry
        # TODO non self-hosted runner - test if using sudo is OK

        # Ensure docker cli is available
        echo "Docker version:"
        sudo docker version --format '{{json .}}'
        echo

        # WARNING : Dockerfile might not be in current directory
        DOCKERFILE_DIR=$( dirname "${{ inputs.docker-file }}" )

        if [[ "${{ inputs.docker-tag-push }}" == "true" ]]; then
          # Build + tag + push

          # Check mandatory inputs
          if [[ -z "${{ inputs.docker-image-prefix }}" ]]; then
            echo "[ERROR] Docker image prefix parameter must not be empty"
            exit 1
          fi

          # Prepare docker image tag prefix
          IMAGE_TAG_PREFIX="${{ inputs.docker-image-prefix }}"
          #echo "IMAGE_TAG_PREFIX: [${IMAGE_TAG_PREFIX}]"

          # Compute tags
          TAGS="${{ inputs.docker-tags }}"
          echo "Tags requested: [${TAGS}]"

          # Convert tags string to an array for easier usage
          declare -a TAGS_ARRAY=( $(echo ${TAGS} | tr ',' ' ') )
          echo "Tags that will be created (array form): [${TAGS_ARRAY[@]}]"
          # DEBUG TAGS_ARRAY contents
          #echo "TAGS_ARRAY length : ${#TAGS_ARRAY[@]}"
          #echo "TAGS_ARRAY[0]: [${TAGS_ARRAY[0]}]"
          #echo "TAGS_ARRAY[1]: [${TAGS_ARRAY[1]}]"
          #echo "TAGS_ARRAY[2]: [${TAGS_ARRAY[2]}]"

          # At least 1 tag is required to be able to tag and push
          if [[ ${#TAGS_ARRAY[@]} -lt 1 ]]; then
            echo "[ERROR] At least one tag must be specified"
            exit 1
          fi

          # Prepare tag options for docker build command
          echo
          FIRST_TAG="${IMAGE_TAG_PREFIX}:${TAGS_ARRAY[0]}"

          # Build and tag
          echo "Docker build file [${{ inputs.docker-file }}]..."

          echo Running: sudo docker build -f "${{ inputs.docker-file }}" -t "${FIRST_TAG}" ${{ inputs.docker-build-other-options }} "${DOCKERFILE_DIR}"
          sudo docker build -f "${{ inputs.docker-file }}" -t "${FIRST_TAG}" ${{ inputs.docker-build-other-options }} "${DOCKERFILE_DIR}"

          # Docker push
          sudo docker push "${FIRST_TAG}"
          echo "DOCKER_PUSHED=true" >> $GITHUB_OUTPUT

          # Re-tag and push other tags
          for (( i=1; i<${#TAGS_ARRAY[@]}; i++ )); do
            echo
            CURRENT_TAG="${IMAGE_TAG_PREFIX}:${TAGS_ARRAY[$i]}"
            #
            echo "Adding tag [${CURRENT_TAG}]..."
            sudo docker tag "${FIRST_TAG}" "${CURRENT_TAG}"
            #
            echo "Pushing tag [${CURRENT_TAG}]..."
            sudo docker push "${CURRENT_TAG}"
            #
            echo "Tag [${CURRENT_TAG}] DONE"
          done
        else
          # Build only
          echo "Docker build file [${{ inputs.docker-file }}]..."
          echo Running: sudo docker build -f "${{ inputs.docker-file }}" ${{ inputs.docker-build-other-options }} "${DOCKERFILE_DIR}"
          sudo docker build -f "${{ inputs.docker-file }}" ${{ inputs.docker-build-other-options }} "${DOCKERFILE_DIR}"
          echo "DOCKER_PUSHED=false" >> $GITHUB_OUTPUT
        fi

        echo
        echo "Docker build file [${{ inputs.docker-file }}] DONE"
      shell: bash
