# Copyright (c) 2024 AVI-SPL Inc.
# All Rights Reserved.
# Prerequisites :
# - GitHub actions from AVI-SPL private repository must be available in local workspace directory
#
name: 'Send Generic Email'
description: 'given all required fields, this action generates and sends email'

inputs:
  builderSmtpHost:
    description: 'The SMTP server host address'
    required: true
  emailTo:
    description: 'The To email address'
    required: true
  emailFrom:
    description: 'The From email display name'
    required: true
  body:
    description: 'The body of email in HTML format'
    required: true
  subject:
    description: 'The subject of email'
    required: true

runs:
  using: "composite"
  steps:
    - name: Send mail
      uses: dawidd6/action-send-mail@v3.11.0
      with:
       server_address: ${{inputs.builderSmtpHost}}
       ignore_cert: true
       secure: false
       subject: ${{inputs.subject}}
       to: ${{inputs.emailTo}}
       from: ${{inputs.emailFrom}}
       html_body: file://${{inputs.body}}