# Copyright (c) 2022 AVI-SPL Inc.
# All Rights Reserved.
#
name: 'Setup Maven Settings'
description: |
  Reusable action to help with configuring Maven within a given workflow

inputs:
  nexus-user:
    description: 'username of nexus user'
    required: true
  nexus-password:
    description: 'password of nexus user'
    required: true
env:
  NEXUS_USER: ${{ inputs.nexus-user }}
  NEXUS_PASSWORD: ${{ inputs.nexus-password }}
runs:
  using: "composite"
  steps:
    - name: Setup Maven
      uses: s4u/maven-settings-action@v2.7.0
      with:
        servers: |
          [{
            "id": "avi-spl.snapshots",
            "username": "${NEXUS_USER}",
            "password": "${NEXUS_PASSWORD}"
          },{
            "id": "avi-spl.releases",
            "username": "${NEXUS_USER}",
            "password": "${NEXUS_PASSWORD}"
          }]
