# Copyright (c) 2022 AVI-SPL Inc.
# All Rights Reserved.
#
# Perform a Maven build and optionally add Git tag
# Prerequisites:
# - JDK must be available
name: 'Maven build (Git tag)'
description: 'Maven build and optionally add Git tag'

inputs:
  # Maven options
  pom-xml-file:
    description: 'The path of the project pom.xml'
    required: true
  maven_goals:
    description: 'The goals for the mvn command'
    required: false
    default: clean install
  maven_other_options:
    description: 'Maven options added at the end of the mvn command, overrides previous options'
    required: false
    default: ''
  # Git tag options
  git_tag:
    description: 'Tag to be created on Git revision, e.g. "snapshot" for daily build. Empty means no tag'
    required: false
    default: ''
  git_tag_fail_if_exists:
    description: >
      Used only when a Git tag name is provided by parameter git_tag
      A security to avoid overwriting tags by mistake
      If tag exists and value is not 'false', fail the job
      Otherwise, has no effect
    required: true
    default: 'true'
  git_delete_tag_if_exists:
    description: >
      Used only when a Git tag name is provided by parameter git_tag
      If value is 'true': delete existing Git tag with name $git_tag.
      If tag does not exist, do nothing
      If value is different from 'true', do nothing
    required: false
    default: 'false'
  github_token:
    description: >
      Used only when a Git tag name is provided by parameter git_tag
      GitHub secret token to be provided by caller
    required: false
runs:
  using: 'composite'
  steps:
    - name: Maven build
      # Option -U (or --update-snapshots)
      #   Forces a check for missing releases and updated snapshots on remote repositories
      #   Required because using caching of Maven dependencies
      run: mvn -B -U --file ${{ inputs.pom-xml-file }} ${{ inputs.maven_goals }} ${{ inputs.maven_other_options }}
      shell: bash

    # Remove existing tag (if tagging is requested and tag exists)
    - name: Git tag delete existing
      id: git_tag_delete_existing
      if: "${{ inputs.git_tag != '' && inputs.git_delete_tag_if_exists == 'true' }}"
      uses: ./.github/symphony-devops-workflows/actions/git_delete_tag
      with:
        tag_name: ${{ inputs.git_tag }}
        git_tag_fail_if_exists: ${{ inputs.git_tag_fail_if_exists }}

    # Tag with git_tag (if defined) the currently checkouted Git revision
    - name: Git tag current commit
      if: "${{ inputs.git_tag != '' }}"
      uses: pkgdeps/git-tag-action@v2
      with:
        github_token: ${{ inputs.github_token }}
        github_repo: ${{ github.repository }}
        git_commit_sha: ${{ github.sha }}
        version: ${{ inputs.git_tag }}
        # no prefix added to tag, use tag as it is provided by caller
        git_tag_prefix: ''
