# Copyright (c) 2022 AVI-SPL Inc.
# All Rights Reserved.
#
# Builds, runs tests and deploys a Maven project
# Moves Git tag 'snapshot' to the latest commit on branch
# Checkouts current repository/branch (inherited from caller workflow)
name: reusable_workflow_deploy_branch_maven

on:
  workflow_call:
    inputs:
      maven_goals:
        description: 'The goals for the mvn command (optional)'
        required: false
        type: string
        # TODO fix default maven goals : use "deploy" instead of "install" when everything is OK
        default: 'clean install'
      maven_other_options:
        description: 'Maven options added at the end of the mvn command, overrides previous options'
        required: false
        type: string
        default: '-DskipTests=false -DskipITs=false'
      runs-on_label_1:
        description: 'The job runner first label (optional)'
        required: false
        type: string
        # TODO review runner labels to be used
        default: 'self-hosted'
      runs-on_label_2:
        description: 'The job runner second label (optional)'
        required: false
        type: string
        default: 'linux'
      symphony-devops-workflows_ref:
        description: 'symphony-devops-workflows reference branch (or tag) to be used. E.g. ''main'''
        required: false
        type: string
        default: 'main'
      # Added by shervin
      symphony-microservice-name:
        description: 'symphony-microservice-name is used by shell script to build and tag docker image'
        required: true
        type: string
        default: ''

jobs:
  reusable_job_deploy_branch_maven:
    # Use runner which has requested labels
    # Note: GitHub does not allow to pass an object as job input (such as an array)
    # so need this trick with multiple variables
    runs-on: [ "${{ inputs.runs-on_label_1 }}", "${{ inputs.runs-on_label_2 }}" ]
    steps:
      # WARNING checkout repository first because this action resets the checkout directory
      # (so other files written into it will be removed)
      - name: Git checkout current repository/branch
        uses: actions/checkout@v2
        with:
          # Checkout all branches and tags (required to work with tags in git_delete_tag action)
          fetch-depth: '0' # 0 indicates all history for all branches and tags

      # GitHub actions cannot be executed directly from private repository
      # (feature not available yet)
      # So checkout the actions into local workspace directory and run them from there
      - name: Checkout actions from private repository
        uses: actions/checkout@v2
        with:
          repository: AVISPL/symphony-devops-workflows
          # Select revision
          ref: '${{ inputs.symphony-devops-workflows_ref }}'
          # Indicate where to checkout project to
          path: ./.github/symphony-devops-workflows

      - name: Setup JDK
        uses: ./.github/symphony-devops-workflows/actions/setup_jdk
        with:
          java-version: 16
          distribution: adopt # Adopt OpenJDK

      - name: Maven build and Git tag
        uses: ./.github/symphony-devops-workflows/actions/maven_build_and_tag
        with:
          # Maven options
          #maven_goals: ${{ inputs.maven_goals }}
          #maven_other_options: ${{ inputs.maven_other_options }}
          # Git tag options
          # TODO should tag options be parameterized with inputs as the caller job knows
          # what triggered it ?
          git_tag: 'snapshot'
          git_tag_fail_if_exists: 'false'
          git_delete_tag_if_exists: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # check out repo from github so job can access it
      
      # ADDED by Shervin: run shell script to build and push docker image to harbor
      - name: script to build and push docker image to harbor
        shell: bash
        #run: sh ./.github/symphony-devops-workflows/scripts/build_and_deploy_docker_image_to_harbor.sh -m ${{ inputs.symphony-microservice-name }}
        run: |
          pwd
          ls -al .github/
          chmod +x ././.github/symphony-devops-workflows/scripts/build_and_deploy_docker_image_to_harbor.sh
          ././.github/symphony-devops-workflows/scripts/build_and_deploy_docker_image_to_harbor.sh -m ${{ inputs.symphony-microservice-name }}
          
  # Job to send email - execute event when previous job(s) in workflow have failed
  job_send_mail:
    # For details on if condition when previous job is skipped and there is a needs condition,
    # see discussions here:
    # https://github.com/actions/runner/issues/491#issuecomment-926924523
    if: ${{ !cancelled() }}
    runs-on: [ "${{ inputs.runs-on_label_1 }}", "${{ inputs.runs-on_label_2 }}" ]
    needs: reusable_job_deploy_branch_maven
    steps:
      - name: Send email workflow status
        uses: ./.github/symphony-devops-workflows/actions/send_email_workflow_status
